# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchToy' do
	platform :osx, '10.11'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DFSearchKit', :path => '../'
end

target 'dfsearchindex' do
  platform :osx, '10.11'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'DFSearchKit', :path => '../'
end
